### ISSUE TITLE
failed to install pam_radius - depency issue

### ISSUE THREAD

**Issue by asifiqbal** [techdad/puppet-pamradius#2]
Need to install epel-release to find pam_radius. Adding that package first fixes it

package { 'epel-release':
    ensure => installed,
}

package { 'pam_radius':
  ensure => 'installed',
  require => Package['epel-release']
}

**Comment by techdad** [comment]
Ah, thanks. I'll update this in the next few days, but you are also welcome to send a pull request.

**Comment by techdad** [comment]
commit f9d7e7ab0e338a8c9a45054b6dcad280ca9ef339
